### ISSUE TITLE
关于手机录音识别的问题

### ISSUE THREAD

**Issue by wangbq18** [jiay7/wenet_onlinedeocde#1]
您好，我试了您的demo.py 使用aishell 的数据没有任何问题，很棒，但是当我用这个demo识别我自己用手机录的音频时，结果完全不对，这个是是么原因呢。录音是.mp3格式，转成了.wav

**Comment by jiay7** [comment]
您要仔细检查一下音频转换过后的采样率，手机录制的一般为44100Hz。另外如果测试实地录制的音频，最好加大训练的数据集规模。

**Comment by wangbq18** [comment]
> 您要仔细检查一下音频转换过后的采样率，手机录制的一般为44100Hz。另外如果测试实地录制的音频，最好加大训练的数据集规模。

感谢回答，已经解决
